from typing import Optional, Any
from typing_extensions import TypedDict


class BotState(TypedDict, total=False):
    # ── Content ───────────────────────────────────────────────────────────────
    german_word: str                  # raw word selected by LLM, e.g. "Führerschein"
    article: str                      # "der" / "die" / "das" / "no known noun"
    cefr_level: str                   # "A1" … "C1"
    word_emoji: str                   # emoji for the word (doubled in tweet)
    translated_word: str              # English translation of the word
    example_sentence_de: str          # German example sentence
    example_sentence_en: str          # English translation of example sentence
    sentence_emoji: str               # emoji for the sentence (doubled in tweet)
    full_tweet: str                   # assembled final tweet text

    # ── Image ─────────────────────────────────────────────────────────────────
    midjourney_prompt: str            # Midjourney prompt generated by LLM
    image_path: str                   # path to chosen PNG

    # ── Audio ─────────────────────────────────────────────────────────────────
    clean_audio_path: str             # path to raw TTS MP3
    word_timings: list                # [{word, start, end}, …] for ktv highlighting
    mixed_audio_path: str             # path to voice + background music MP3

    # ── Video ─────────────────────────────────────────────────────────────────
    video_path: str                   # path to final MP4

    # ── Publishing ────────────────────────────────────────────────────────────
    tweet_id: str                     # ID of the posted tweet
    tweet_url: str                    # URL of the posted tweet

    # ── Metrics ───────────────────────────────────────────────────────────────
    metrics: dict                     # raw tweepy metrics dict
    engagement_score: float           # weighted engagement score

    # ── Strategy ──────────────────────────────────────────────────────────────
    strategy: dict                    # LLM-updated strategy fed into generate_content
    cycle: int                        # how many full cycles completed

    # ── Error handling ────────────────────────────────────────────────────────
    error: Optional[str]              # last error message (if any)
