"""
BotState — the single state dict passed through every graph node.

Keys here are read/written by the nodes in graph.py.  If you add or rename a
key, update all nodes that use it (generate_content, generate_image,
generate_audio, create_video, publish, score_and_store, analyze_and_improve,
fetch_all_metrics).
"""

from typing import Optional, Any
from typing_extensions import TypedDict


class BotState(TypedDict, total=False):
    # ── Content ───────────────────────────────────────────────────────────────
    source_word: str                  # raw word selected by LLM, e.g. "Führerschein"
    article: str                      # grammatical article, e.g. "der" / "la" / "no known noun"
    cefr_level: str                   # "A1" … "C2"
    example_sentence_source: str      # example sentence in the source language
    example_sentence_target: str      # translation of the example sentence in the target language
    full_tweet: str                   # assembled final tweet text

    # ── Image ─────────────────────────────────────────────────────────────────
    midjourney_prompt: str            # Midjourney prompt generated by LLM
    image_path: str                   # path to chosen PNG
    image_subject_gender: str         # "male" | "female" | "neutral" — for TTS voice matching

    # ── Audio ─────────────────────────────────────────────────────────────────
    clean_audio_path: str             # path to raw TTS MP3
    word_timings: list                # [{word, start, end}, …] for ktv highlighting
    mixed_audio_path: str             # path to voice + background music MP3

    # ── Video ─────────────────────────────────────────────────────────────────
    video_path: str                   # path to final MP4

    # ── Publishing ────────────────────────────────────────────────────────────
    tweet_id: str                     # ID of the posted tweet
    tweet_url: str                    # URL of the posted tweet

    # ── Metrics ───────────────────────────────────────────────────────────────
    metrics: dict                     # raw tweepy metrics dict
    engagement_score: float           # weighted engagement score

    # ── Strategy ──────────────────────────────────────────────────────────────
    strategy: dict                    # LLM-updated strategy fed into generate_content
    metrics_refreshed: bool           # True if metrics were fetched this cycle; False if throttled
    cycle: int                        # how many full cycles completed
    used_trend: str                   # trend headline when word came from trends path (else "")
    pool_theme: str                   # curated theme string when USE_TRENDS cycle was pool (else "")

    # ── Error handling ────────────────────────────────────────────────────────
    error: Optional[str]              # last error message (if any)
